services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - wordpress:/var/www/wordpress
  #verif si depend_on utile
    depends_on:
      - wordpress
    networks:
      - inception
 
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env #file for variables
    volumes:
      - mariadb:/var/lib/mysql
    networks: #which network does it belong
      - inception
    restart: unless-stopped #restart if not stopped
    # expose:
    #   - "3306"

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: on-failure


volumes:
  wordpress:
    driver: local #local storage of volume
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jewu/data/wordpress' #where it will be stored locally
  
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind' #bind mounting = volumes mounting on access path to host and can be modified by other processes outisde of Docker 
      device: '/home/jewu/data/mysql'

networks:
  inception:
    driver: bridge #install rules that allow the 3 containers to communicate in bridge